#!/usr/bin/env bash
# ==============================================================================
# deploy.sh — HuntMyDeal Production Deploy Script
#
# Usage: ./deploy.sh
#
# Prerequisites (one-time VPS setup):
#   See docs/vps-setup.md for instructions on storing secrets on the VPS.
#
# What this script does:
#   1. Validates that all required secrets are set as VPS env vars
#   2. Writes .env.production from those env vars (never stored in git)
#   3. Pulls the latest code from git
#   4. Rebuilds and restarts the Docker container
# ==============================================================================

set -euo pipefail

# ── Colours ───────────────────────────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m' # No Colour

info()    { echo -e "${CYAN}[INFO]${NC}  $*"; }
success() { echo -e "${GREEN}[OK]${NC}    $*"; }
warn()    { echo -e "${YELLOW}[WARN]${NC}  $*"; }
error()   { echo -e "${RED}[ERROR]${NC} $*"; exit 1; }

# ── Step 1: Validate required secrets ─────────────────────────────────────────
info "Checking required environment variables..."

REQUIRED_VARS=(
  "HUNTMYDEAL_SUPABASE_URL"
  "HUNTMYDEAL_SUPABASE_ANON_KEY"
  "HUNTMYDEAL_SUPABASE_SERVICE_ROLE_KEY"
  "HUNTMYDEAL_BASE_URL"
)

MISSING=()
for VAR in "${REQUIRED_VARS[@]}"; do
  if [[ -z "${!VAR:-}" ]]; then
    MISSING+=("$VAR")
  fi
done

if [[ ${#MISSING[@]} -gt 0 ]]; then
  error "Missing required VPS environment variables:\n$(printf '  - %s\n' "${MISSING[@]}")\n\nSee docs/vps-setup.md to configure them."
fi

success "All secrets present."

# ── Step 2: Write .env.production ─────────────────────────────────────────────
info "Writing .env.production..."

cat > .env.production <<EOF
# Auto-generated by deploy.sh — DO NOT EDIT MANUALLY
# Generated at: $(date -u '+%Y-%m-%dT%H:%M:%SZ')

NEXT_PUBLIC_SUPABASE_URL=${HUNTMYDEAL_SUPABASE_URL}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${HUNTMYDEAL_SUPABASE_ANON_KEY}
SUPABASE_SERVICE_ROLE_KEY=${HUNTMYDEAL_SUPABASE_SERVICE_ROLE_KEY}
NEXT_PUBLIC_BASE_URL=${HUNTMYDEAL_BASE_URL}
EOF

chmod 600 .env.production
success ".env.production written (permissions: 600)."

# ── Step 3: Pull latest code ───────────────────────────────────────────────────
info "Pulling latest code from git..."
git pull origin main
success "Code updated."

# ── Step 4: Rebuild and restart Docker ────────────────────────────────────────
info "Building and restarting Docker container..."

docker compose --env-file .env.production up --build -d

success "Container rebuilt and running."

# ── Done ──────────────────────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}✔ Deploy complete!${NC}"
echo -e "  App:      ${HUNTMYDEAL_BASE_URL}"
echo -e "  Supabase: ${HUNTMYDEAL_SUPABASE_URL}"
echo ""
