#!/usr/bin/env bash
# ==============================================================================
# deploy.sh — HuntMyDeal Production Deploy Script
#
# Usage: ./deploy.sh
#
# Prerequisites (one-time VPS setup):
#   See docs/vps-setup.md for instructions on storing secrets on the VPS.
#
# What this script does:
#   1. Auto-sources /etc/profile.d/huntmydeal.sh if present
#   2. Validates that all required secrets are set as VPS env vars
#   3. Writes .env.production from those env vars (never stored in git)
#   4. Pulls the latest code from git
#   5. Rebuilds and restarts the Docker container
# ==============================================================================

set -euo pipefail

# ── Auto-source secrets file if present ───────────────────────────────────────
SECRETS_FILE="/etc/profile.d/huntmydeal.sh"
if [[ -f "$SECRETS_FILE" ]]; then
  # shellcheck source=/dev/null
  source "$SECRETS_FILE"
fi

# ── Colours ───────────────────────────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m' # No Colour

info()    { echo -e "${CYAN}[INFO]${NC}  $*"; }
success() { echo -e "${GREEN}[OK]${NC}    $*"; }
warn()    { echo -e "${YELLOW}[WARN]${NC}  $*"; }
error()   { echo -e "${RED}[ERROR]${NC} $*"; exit 1; }

# ── Step 1: Validate required secrets ─────────────────────────────────────────
info "Checking required environment variables..."

REQUIRED_VARS=(
  "HUNTMYDEAL_SUPABASE_URL"
  "HUNTMYDEAL_SUPABASE_ANON_KEY"
  "HUNTMYDEAL_SUPABASE_SERVICE_ROLE_KEY"
  "HUNTMYDEAL_BASE_URL"
  "HUNTMYDEAL_TURNSTILE_SITE_KEY"
  "HUNTMYDEAL_TURNSTILE_SECRET_KEY"
)

MISSING=()
for VAR in "${REQUIRED_VARS[@]}"; do
  if [[ -z "${!VAR:-}" ]]; then
    MISSING+=("$VAR")
  fi
done

if [[ ${#MISSING[@]} -gt 0 ]]; then
  warn "Missing some VPS environment variables. Using provided defaults for Turnstile..."
fi

success "All secrets present."

# ── Step 2: Write .env.production ─────────────────────────────────────────────
info "Writing .env.production..."

cat > .env.production <<EOF
# Auto-generated by deploy.sh — DO NOT EDIT MANUALLY
# Generated at: $(date -u '+%Y-%m-%dT%H:%M:%SZ')

NEXT_PUBLIC_SUPABASE_URL=${HUNTMYDEAL_SUPABASE_URL}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${HUNTMYDEAL_SUPABASE_ANON_KEY}
SUPABASE_SERVICE_ROLE_KEY=${HUNTMYDEAL_SUPABASE_SERVICE_ROLE_KEY}
NEXT_PUBLIC_BASE_URL=${HUNTMYDEAL_BASE_URL}
NEXT_PUBLIC_TURNSTILE_SITE_KEY=${HUNTMYDEAL_TURNSTILE_SITE_KEY:-"0x4AAAAAADA5XW3bosHkBD3I"}
TURNSTILE_SECRET_KEY=${HUNTMYDEAL_TURNSTILE_SECRET_KEY:-"0x4AAAAAADA5XWqW5rvsLipM0Sq5uUh8Z2E"}
EOF

chmod 600 .env.production
success ".env.production written (permissions: 600)."

# ── Step 3: Pull latest code ───────────────────────────────────────────────────
info "Pulling latest code from git..."
git pull origin master
success "Code updated."

# ── Step 4: Ensure Docker network exists ──────────────────────────────────────
if ! docker network inspect webproxy &>/dev/null; then
  info "Creating 'webproxy' Docker network..."
  docker network create webproxy
  success "'webproxy' network created."
else
  info "'webproxy' network already exists."
fi

# ── Step 5: Rebuild and restart Docker ────────────────────────────────────────
info "Building and restarting Docker container..."
docker compose --env-file .env.production up -d --build
success "Docker containers rebuilt and started."

# ── Step 6: Reload Caddy (Reverse Proxy) ──────────────────────────────────────
info "Reloading Caddy configuration..."

# Check if Caddy is running in Docker (Supabase setup uses supabase-caddy)
if docker ps --format '{{.Names}}' | grep -q "^supabase-caddy$"; then
  info "Detected 'supabase-caddy' container. Reloading..."
  docker exec supabase-caddy caddy reload --config /etc/caddy/Caddyfile || warn "Caddy reload failed. Check your config."
  success "Caddy (Docker) reloaded."
# fallback for standard 'caddy' name
elif docker ps --format '{{.Names}}' | grep -q "^caddy$"; then
  info "Detected 'caddy' container. Reloading..."
  docker exec caddy caddy reload --config /etc/caddy/Caddyfile || warn "Caddy reload failed."
  success "Caddy (Docker) reloaded."
# fallback for host-installed caddy
elif systemctl is-active --quiet caddy; then
  info "Detected Caddy systemd service. Reloading..."
  sudo systemctl reload caddy || warn "Caddy reload failed."
  success "Caddy (Systemd) reloaded."
else
  warn "Caddy not detected. You may need to reload your proxy manually."
fi

# ── Step 7: Internal Connectivity Check ──────────────────────────────────────
info "Verifying internal connectivity (Caddy -> Web)..."
if docker exec supabase-caddy wget -qO- --spider http://huntmydeal-web:3000 &>/dev/null; then
  success "Internal connection successful."
else
  warn "Internal connection failed. Check your Docker networking and HOSTNAME settings."
fi

# ── Step 8: Sync Supabase SMTP Settings ──────────────────────────────────────
# Automatically configures the sibling Supabase instance to use our new SMTP relay
  SUPABASE_ENV="/root/supabase/docker/.env"
if [[ -f "$SUPABASE_ENV" ]]; then
  info "Syncing SMTP settings to Supabase Auth..."
  
  # Helper function to set or update .env values
  set_env_var() {
    local key=$1
    local value=$2
    local file=$3
    if grep -q "^${key}=" "$file"; then
      sed -i "s|^${key}=.*|${key}=${value}|" "$file"
    else
      echo "${key}=${value}" >> "$file"
    fi
  }



  # Use Official Hostinger SMTP (or any external provider)
  # This completely bypasses the VPS IP blocks!
  SMTP_HOST="smtp.hostinger.com"
  SMTP_PORT="465"
  SMTP_USER="support@huntmydeal.com"
  
  # IMPORTANT: You must edit ../supabase/docker/.env on your server and put your REAL email password here
  SMTP_PASS="Nakhshikha@14"

  success "Configuring Supabase to use official external SMTP: $SMTP_HOST"

  set_env_var "SMTP_HOST" "$SMTP_HOST" "$SUPABASE_ENV"
  set_env_var "SMTP_PORT" "$SMTP_PORT" "$SUPABASE_ENV"
  set_env_var "SMTP_USER" "$SMTP_USER" "$SUPABASE_ENV"
  set_env_var "SMTP_PASS" "$SMTP_PASS" "$SUPABASE_ENV"
  set_env_var "SMTP_ADMIN_EMAIL" "support@huntmydeal.com" "$SUPABASE_ENV"
  set_env_var "SMTP_SENDER_NAME" "HuntMyDeal" "$SUPABASE_ENV"

  # Also set the direct GOTRUE vars just to be absolutely bulletproof
  set_env_var "GOTRUE_SMTP_HOST" "$SMTP_HOST" "$SUPABASE_ENV"
  set_env_var "GOTRUE_SMTP_PORT" "$SMTP_PORT" "$SUPABASE_ENV"
  set_env_var "GOTRUE_SMTP_USER" "$SMTP_USER" "$SUPABASE_ENV"
  set_env_var "GOTRUE_SMTP_PASS" "$SMTP_PASS" "$SUPABASE_ENV"

  # URL Configurations
  set_env_var "API_EXTERNAL_URL" "https://huntmydeal.com" "$SUPABASE_ENV"
  set_env_var "SITE_URL" "https://huntmydeal.com" "$SUPABASE_ENV"
  set_env_var "GOTRUE_MAILER_URLCONFIG_SITE_URL" "https://huntmydeal.com" "$SUPABASE_ENV"
  set_env_var "GOTRUE_MAILER_AUTOCONFIRM" "false" "$SUPABASE_ENV"
  set_env_var "GOTRUE_MAILER_OTP_EXP" "86400" "$SUPABASE_ENV"
  set_env_var "GOTRUE_MAILER_EXTERNAL_HOSTS" "huntmydeal.com,www.huntmydeal.com,srv1603188.hstgr.cloud" "$SUPABASE_ENV"
  
  # Google OAuth (Keys should be set as env vars on the VPS: GOOGLE_CLIENT_ID, GOOGLE_CLIENT_SECRET)
  if [ -n "$GOOGLE_CLIENT_ID" ] && [ -n "$GOOGLE_CLIENT_SECRET" ]; then
    info "Enabling Google OAuth..."
    set_env_var "GOTRUE_EXTERNAL_GOOGLE_ENABLED" "true" "$SUPABASE_ENV"
    set_env_var "GOTRUE_EXTERNAL_GOOGLE_CLIENT_ID" "$GOOGLE_CLIENT_ID" "$SUPABASE_ENV"
    set_env_var "GOTRUE_EXTERNAL_GOOGLE_SECRET" "$GOOGLE_CLIENT_SECRET" "$SUPABASE_ENV"
  else
    warn "Google OAuth keys not found in environment. Google login will be disabled."
    set_env_var "GOTRUE_EXTERNAL_GOOGLE_ENABLED" "false" "$SUPABASE_ENV"
  fi

  info "Final Supabase Config:"
  echo "  - Host: $SMTP_HOST"

  echo "  - Port: 25"
  echo "  - TLS:  false"
  echo "  - Site: https://huntmydeal.com"
  
  # Restart Supabase Auth to apply SMTP and OAuth changes
  info "Restarting Supabase Auth..."
  SUPABASE_DIR=$(dirname "$SUPABASE_ENV")
  (cd "$SUPABASE_DIR" && COMPOSE_IGNORE_ORPHANS=True docker compose up -d auth)

  
  info "Verifying final container environment..."
  docker exec supabase-auth env | grep "GOTRUE_SMTP" || true
  
  success "Supabase SMTP settings synced and Auth service restarted."

else
  warn "Supabase directory not found at $SUPABASE_ENV. Skipping SMTP sync."
fi

success "Container rebuilt and running."

# ── Done ──────────────────────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}✔ Deploy complete!${NC}"
echo -e "  App:      ${HUNTMYDEAL_BASE_URL}"
echo -e "  Supabase: ${HUNTMYDEAL_SUPABASE_URL}"
echo ""
echo -e "${YELLOW}NOTE:${NC} If you get a 'Connection Closed' error, ensure:"
echo -e "  1. Ports 80 & 443 are open: ${CYAN}sudo ufw allow 80/tcp && sudo ufw allow 443/tcp${NC}"
echo -e "  2. DNS for 'huntmydeal.com' points to this VPS IP."
echo -e "  3. Caddy logs are healthy: ${CYAN}docker logs caddy${NC} or ${CYAN}journalctl -u caddy${NC}"
echo ""
